<?php


/**
 * @file
 * Examples demonstrating the Drupal Form API with Ajax.
 */

/**
 * Implements hook_menu().
 *
 */
function form_validacja_menu() {
 
  $items = array();
 
  $items['form_validacja'] = array(
    'title' => 'Validacja',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_validacja_form'),
    'menu_name' => 'main-menu',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
    );

  return $items;
}
/**
 * Implements hook_form().
 *
 */
function form_validacja_form($form, &$form_state) {

  $form = array();
  
  $form['#prefix'] = '<div id="formwrapper">';
  $form['#suffix'] = '</div>';

  $form["name"] = array(
    "#type" => "textfield", 
    "#required" => TRUE,
    "#title" => "Name",
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['submit']['#ajax'] = array(
    'callback' => 'form_validate_submit',
    'wrapper' => 'formwrapper',
    'method' => 'replace',
    'effect' => 'fade',
  );
  return $form;

}


function form_validate_submit($form, &$form_state) {

  drupal_validate_form('form-validacja-form', $form, $form_state);

   if (form_get_errors()) {

    $form_state['rebuild'] = TRUE;

    return $form;

  }

  $output = array(

    '#markup' => 'Form submitted.'

  );

  return $output;
  
}